name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: desktop:dist
        gradle-version: 5.6.2
    - uses: actions/upload-artifact@v1
      with:
        name: desktop.jar
        path: ./desktop/build/libs/desktop-1.0.jar
