name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: desktop:dist
        gradle-version: 5.6.2
    - name: Generate Desktop build
      run: java -jar packr.jar packr-config.win64.json
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'win64.zip'
        basepath: 'out-win64'
    - uses: xresloader/upload-to-github-release@v1
      id: upload_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "./desktop/build/libs/desktop-1.0.jar;win64.zip"
        prerelease: true
        draft: false
